- name: 'bump:major'
  color: ef6bb4
  description: 'Attach to PR to automatically bump major version on merge'
  aliases: [ ]

- name: 'bump:minor'
  color: ef6bb4
  description: 'Attach to PR to automatically bump minor version on merge'
  aliases: [ ]

- name: 'bump:patch'
  color: ef6bb4
  description: 'Attach to PR to automatically bump patch version on merge'
  aliases: [ ]

- name: 'automation'
  color: 3ddd1b
  description: 'Removing manual tasks by automating them'
  aliases: [ ]

- name: 'bug'
  color: d73a4a
  description: 'Something is not working'
  aliases: [ ]

- name: 'documentation'
  color: 0075ca
  description: 'Improvements or additions to documentation'
  aliases: [ ]

- name: 'enhancement'
  color: a2eeef
  description: 'New feature or request'
  aliases: [ ]
