repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_validate
        exclude: '^[^/]+$'
      - id: terraform_tflint
        exclude: ^examples/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
